#Note: do not build prod docker and database container on dev-branches 
version: '3.8'

services:
  app_prod:
    build:
      context: .
      dockerfile: app.dockerfile  # Production Dockerfile használata
    environment:
      - PORT=8001
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=proddb
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - app-network

  app_dev:
    build:
      context: .
      dockerfile: app.dockerfile  # Development Dockerfile használata
    environment:
      - PORT=8002
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=devdb
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8002:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proddb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

