version: '3.8'

services:
  #Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - PORT=8000  # A gunicorn indítási portja
      - DB_USER=testuser
      - DB_PASSWORD=testpassword
      - DB_NAME=testdb
      - DB_HOST=db  # Docker szolgáltatás neve a MySQL adatbázishoz
      - DB_PORT=3306
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword

    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

