version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_HOST=db  # Docker szolgáltatás neve a MySQL adatbázishoz
      - DB_PORT=3306
      - PORT=8000  # Ensure the app listens on port 8000
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    env_file:
      - .env  # Reference the .env file
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 
