"""Initial migration

Revision ID: 0b4166a6b7eb
Revises: 4cd5c245714f
Create Date: 2024-09-17 21:27:55.274899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4166a6b7eb'
down_revision: Union[str, None] = '4cd5c245714f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Company')
    op.drop_table('Slot')
    op.drop_table('Customer')
    op.drop_table('Extra')
    op.drop_table('Reservation')
    op.drop_table('Billing')
    op.drop_table('Service')
    op.drop_table('User')
    op.drop_table('Car')
    op.drop_table('reservation_extra')
    op.drop_table('Carwash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carwash',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('carwash_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('close_start', sa.DATETIME(), nullable=True),
    sa.Column('close_end', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_extra',
    sa.Column('reservation_id', sa.INTEGER(), nullable=False),
    sa.Column('extra_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['extra_id'], ['Extra.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservation.id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'extra_id')
    )
    op.create_table('Car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=15), nullable=False),
    sa.Column('car_type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('car_brand', sa.VARCHAR(length=30), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=512), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('carwash_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['carwash_id'], ['Carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('price_small', sa.INTEGER(), nullable=False),
    sa.Column('price_large', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('carwash_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['carwash_id'], ['Carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Billing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('reservation_id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tax_ID', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slot_id', sa.INTEGER(), nullable=False),
    sa.Column('car_id', sa.INTEGER(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('carwash_id', sa.INTEGER(), nullable=False),
    sa.Column('reservation_date', sa.DATETIME(), nullable=False),
    sa.Column('parking_spot', sa.INTEGER(), nullable=True),
    sa.Column('final_price', sa.FLOAT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['Car.id'], ),
    sa.ForeignKeyConstraint(['carwash_id'], ['Carwash.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Service.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['Slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Extra',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('extra_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('carwash_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['Carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('forname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Slot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('live', sa.BOOLEAN(), nullable=True),
    sa.Column('carwash_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['carwash_id'], ['Carwash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('discount', sa.DOUBLE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
